services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - my-network
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

    depends_on:
      - zookeeper
    networks:
      - my-network

  msa:
    build:
      context: ./msa  # The path to the msa directory with a Dockerfile
      dockerfile: Dockerfile
    container_name: msa
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  msb:
    build:
      context: ./msb  # The path to the msb directory with a Dockerfile
      dockerfile: Dockerfile
    container_name: msb
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  msc:
    build:
      context: ./msc  # The path to the msb directory with a Dockerfile
      dockerfile: Dockerfile
    container_name: msc
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      - kafka
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  gateway:
    build:
      context: ./gateway # The path to the gateway directory with a Dockerfile
      dockerfile: Dockerfile
    container_name: gateway-container
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: kafka:9093
      HOST_URI: host.docker.internal

    depends_on:
      - msa
      - msb
      - msc
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  my-network:
    driver: bridge
