apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
    bb: web  # Added to match the Deployment label
  ports:
    - protocol: TCP
      port: 80          # Port on which the service is exposed
      targetPort: 9090  # Port on which the container is listening
      nodePort: 30001   # Specify a node port (optional, used with LoadBalancer or NodePort type)
  type: LoadBalancer
