apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      bb: web
      app: gateway
  template:
    metadata:
      labels:
        bb: web
        app: gateway
    spec:
      containers:
        - name: gateway
          image: guedadachraf/gatewayservice:1.1  # Replace with your Gateway Docker image
          ports:
            - containerPort: 9090  # Port on which the application listens
