apiVersion: v1
kind: Service
metadata:
  name: msb-service
spec:
  selector:
    app: msb
  ports:
    - protocol: TCP
      port: 80       # The port that will be exposed externally
      targetPort: 8082 # The port on the container
  type: LoadBalancer
