apiVersion: v1
kind: Service
metadata:
  name: msa-service
  labels:
    app: msa
spec:
  type: LoadBalancer
  selector:
    app: msa
  ports:
    - protocol: TCP
      port: 80           # External port to expose
      targetPort: 8081   # Internal container port that your app listens on
