apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-deployment
  labels:
    app: msa
spec:
  replicas: 3  # Number of replicas you want to run
  selector:
    matchLabels:
      app: msa
  template:
    metadata:
      labels:
        app: msa
    spec:
      containers:
        - name: msa-container
          image: guedadachraf/msbservice:latest  # Replace with your image name
          ports:
            - containerPort: 8081  # Port your application is running on
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production  # Set any environment variables your app needs
